### PR TITLE
fix: refactor library to prepare for v3

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR takes all the unrelated v3 structural changes from https://github.com/asyncapi/converter-js/pull/163 and adds them to a single PR to make the v3 changes easier to review down the line.

All changes are mainly done by @magicmatatjahu, I just clean it up and adapt it to any review comments

### CODE REVIEW

**Comment by jonaslagoni** [comment]
Pretty sure this is just a refactoring without adapting or changing the API of the library nor the underlying converter functionality. 

Thats why I am using `chore`.

**Comment by jonaslagoni** [comment]
Whenever you get some time @fmvilas, think you are the only codeowner that's currently available 😄

**Review by magicmatatjahu — APPROVED** [review]
LGTM

**Review by derberg — APPROVED** [review]
lgtm although with such large refactors I personally always prefer to trigger release to learn early that something is broken 😄 feel free to change to `fix: `

**Comment by jonaslagoni** [comment]
Why not 😄

**Pull request merged**
