### PR TITLE
feat: rewrite to TS and start using Jest

### LINKED ISSUE #106: Rewrite to TS
As most of our tools in which we use converter are written in TS I think it would be a good idea to rewrite converter to TS. The library itself is quite small so it shouldn't be a problem. On the plus side, we will have types for Studio/ServerAPI/CLI.

### LINKED ISSUE #107: Switch to Jest
In most of our projects we use `jest` as a testing framework. In this project (which was one of the first) we use `mocha`. It is not a bad choice but we should be consistent. This should be done after doing this https://github.com/asyncapi/converter-js/issues/106

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

- rewrite package to the TS
- start using Jest 
- expose types
- add needed scripts

> NOTE: PR hasn't any breaking changes. It's old code with TS types.

**Related issue(s)**
Resolves #106 
Resolves #107

### CODE REVIEW

**Comment by magicmatatjahu** [comment]
@derberg 😘  Thanks dude!

I forgot about that `prepublish` script to transpile TS, thanks! 

About CLI I wrote about my plan here https://github.com/asyncapi/converter-js/pull/100#issuecomment-1044283924 So in the next month when we will release `2.4.0` I will remove CLI and release 1.0.0 :)

**Comment by magicmatatjahu** [comment]
@derberg Thanks for review! I added to the Readme example how to use package with exported types and also added `prepublishOnly` script.

**Comment by derberg** [comment]
what about my comment

> I'm also thinking, minimum should be that we release it as feat as you expose 2 new interfaces

**Comment by magicmatatjahu** [comment]
@derberg Sorry, done 😅

**Review by derberg — APPROVED** [review]
:shipit: 

if you want to update it manually in studio, then remember to stop https://github.com/asyncapi/converter-js/actions/workflows/bump.yml after release of converter. Or just block update PR in studio once it is created

**Comment by magicmatatjahu** [comment]
@derberg Thanks for tip, however It won't be needed, because there isn't breaking change :)

**Pull request merged**
