### PR TITLE
ci: upgrade release workflow to new version

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR upgrade the CI to use the new workflows.

Fixes https://github.com/asyncapi/converter-js/issues/178

### CODE REVIEW

**Comment by jonaslagoni** [comment]
One of you codeowners need to set some labels

**Review by derberg — CHANGES_REQUESTED** [review]
please remove `release` script from `package.json` too

regarding `Deprecation of way data is shared between steps` and `Deprecation of node12` there were no changes needed, no custom workflows to review?

**Comment by jonaslagoni** [comment]
> regarding Deprecation of way data is shared between steps and Deprecation of node12 there were no changes needed, no custom workflows to review?

There are no custom workflows, no 🙂

**Review by derberg — APPROVED** [review]

**Comment by derberg** [comment]
new workflows files are also in place now https://github.com/asyncapi/converter-js/pull/182

so @jonaslagoni you can go ahead with followup release PR

**Comment by jonaslagoni** [comment]
@derberg https://github.com/asyncapi/converter-js/pull/183

**Pull request merged**
